# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 # SPDX-License-Identifier: MIT-0
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy of this
 # software and associated documentation files (the "Software"), to deal in the Software
 # without restriction, including without limitation the rights to use, copy, modify,
 # merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 # permit persons to whom the Software is furnished to do so.
 #
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 # INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 # PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 # HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 # OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 # SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 # dev branch

version: 0.2

phases:

  install:
    commands:
      - "apt update"
      - "apt install unzip -y"
      - "apt install net-tools"
 #     - "wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip"
 #     - "unzip terraform_0.11.14_linux_amd64.zip"
 #     - "mv terraform /usr/local/bin/"
 # pre_build:
#    commands:
#      - terraform init -verify-plugins=false
#      - terraform init
#      - terraform workspace list
#      - terraform state list
#      - terraform fmt
#      - terraform validate -backend=false
#      - echo `pwd`
#      - ls -ltra

  build:
    commands:
      - export wrkspace=`echo $PWD`
      - echo $wrkspace
      - ls -ltr
      - git clone https://github.com/rshirke71/ProductLine1_App1_Proj1_Infra.git
      - mkdir modules
      - cd modules
      - git clone https://github.com/rshirke71/terraform-aws-ec2-instance.git
      - cd $wrkspace
      - ls -ltrR
      
      - echo $CODEBUILD_SRC_DIR_source1
      - echo $$CODEBUILD_SRC_DIR_source2
      - cd $CODEBUILD_SRC_DIR_source1
      - echo `pwd`      
      - touch file1
      - ls -ltr
      
      - cd $CODEBUILD_SRC_DIR_source2
      - touch file2
      - echo `pwd`

      - ls -ltra
 #     - docker ps
 #####     - uname -a
 #####     - ifconfig -a
 #     - terraform plan -out plan.out
 ####     - terraform graph | dot -Tpng > graph.png
 #     - terraform state list
 #     - terraform $TF_COMMAND -auto-approve
 
#  artifacts:
#   files:
#    - '**.*'
#  secondary-artifacts:
#    artifact1:
#      base-directory: $CODEBUILD_SRC_DIR_source1
#      files:
#        - file1
#    artifact2:
#      base-directory: $CODEBUILD_SRC_DIR_source2
#      files:
#        - file2

  post_build:
    commands:
#      - echo terraform $TF_COMMAND completed on `date`
       - echo done 
